modLoader="javafml"
loaderVersion="[35,)"
license="MIT License"

[[mods]]
modId="morevanillalib"
version="${file.jarVersion}"
displayName="MoreVanillaLib"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/morevanillalib.json"
authors="MelanX"
description='''
Lib mod for my Vanilla mods:
- MoreVanillaTools
- Vanilla Excavators
- Vanilla Hammers
'''

[[dependencies.morevanillalib]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillalib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4, 1.17)"
    ordering="NONE"
    side="BOTH"
