modLoader="javafml"
loaderVersion = "[42,)"
license = "Apache-2.0"
issueTrackerURL = "https://www.github.com/MelanX/MoreVanillaLib/issues/"

[[mods]]
modId="morevanillalib"
version="${file.jarVersion}"
displayName="MoreVanillaLib"
updateJSONURL="https://assets.melanx.de/updates/morevanillalib.json"
authors="MelanX"
description='''
Lib mod which expands features for my Vanilla mods:
- MoreVanillaTools
- Simply Tools
- Vanilla AIOTs
'''

[[dependencies.morevanillalib]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillalib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1, 1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillalib]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.1-4.1.1,)"
    ordering="AFTER"
    side="BOTH"
