modLoader="javafml"
loaderVersion = "[37,)"
license = "Apache-2.0"

[[mods]]
modId="morevanillalib"
version="${file.jarVersion}"
displayName="MoreVanillaLib"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/morevanillalib.json"
authors="MelanX"
description='''
Lib mod for my Vanilla mods:
- MoreVanillaTools
- Vanilla Excavators
- Vanilla Hammers
- Vanilla AIOTs
'''

[[dependencies.morevanillalib]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillalib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1, 1.18)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillalib]]
    modId="libx"
    mandatory=true
    versionRange="[1.17.1-2.0.5,)"
    ordering="NONE"
    side="BOTH"