modLoader="javafml"
loaderVersion = "[39,)"
license = "Apache-2.0"

[[mods]]
modId="morevanillalib"
version="${file.jarVersion}"
displayName="MoreVanillaLib"
updateJSONURL="https://assets.melanx.de/updates/morevanillalib.json"
authors="MelanX"
description='''
Lib mod for my Vanilla mods:
- MoreVanillaTools
- Vanilla Excavators
- Vanilla Hammers
- Vanilla AIOTs
'''

[[dependencies.morevanillalib]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillalib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1, 1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morevanillalib]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.1-3.1.0,)"
    ordering="NONE"
    side="BOTH"